/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CommandeService } from "../commande.service";
import { CommandeCreateInput } from "./CommandeCreateInput";
import { Commande } from "./Commande";
import { CommandeFindManyArgs } from "./CommandeFindManyArgs";
import { CommandeWhereUniqueInput } from "./CommandeWhereUniqueInput";
import { CommandeUpdateInput } from "./CommandeUpdateInput";

export class CommandeControllerBase {
  constructor(protected readonly service: CommandeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Commande })
  async createCommande(
    @common.Body() data: CommandeCreateInput
  ): Promise<Commande> {
    return await this.service.createCommande({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Commande] })
  @ApiNestedQuery(CommandeFindManyArgs)
  async commandes(@common.Req() request: Request): Promise<Commande[]> {
    const args = plainToClass(CommandeFindManyArgs, request.query);
    return this.service.commandes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Commande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async commande(
    @common.Param() params: CommandeWhereUniqueInput
  ): Promise<Commande | null> {
    const result = await this.service.commande({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Commande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCommande(
    @common.Param() params: CommandeWhereUniqueInput,
    @common.Body() data: CommandeUpdateInput
  ): Promise<Commande | null> {
    try {
      return await this.service.updateCommande({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Commande })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCommande(
    @common.Param() params: CommandeWhereUniqueInput
  ): Promise<Commande | null> {
    try {
      return await this.service.deleteCommande({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
