/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Produit } from "./Produit";
import { ProduitCountArgs } from "./ProduitCountArgs";
import { ProduitFindManyArgs } from "./ProduitFindManyArgs";
import { ProduitFindUniqueArgs } from "./ProduitFindUniqueArgs";
import { DeleteProduitArgs } from "./DeleteProduitArgs";
import { ProduitService } from "../produit.service";
@graphql.Resolver(() => Produit)
export class ProduitResolverBase {
  constructor(protected readonly service: ProduitService) {}

  async _produitsMeta(
    @graphql.Args() args: ProduitCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Produit])
  async produits(
    @graphql.Args() args: ProduitFindManyArgs
  ): Promise<Produit[]> {
    return this.service.produits(args);
  }

  @graphql.Query(() => Produit, { nullable: true })
  async produit(
    @graphql.Args() args: ProduitFindUniqueArgs
  ): Promise<Produit | null> {
    const result = await this.service.produit(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Produit)
  async deleteProduit(
    @graphql.Args() args: DeleteProduitArgs
  ): Promise<Produit | null> {
    try {
      return await this.service.deleteProduit(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
